#issue-1: докер контейнер собирается и запускается. В pom добавлен sp…
intabia-intership/wikitabia-telegram-bot pull request #2
Opened 2022-04-22 06:17 UTC by MudryPryanik

…ring boot maven plugin и конфигурации annotation processors для lombok и mapstruct

2022-04-22 06:55 UTC, Nepomnyaschy submitted a review, later dismissed

2022-04-22 08:22 UTC, Frechet commented
Исправь, пожалуйста. тект коммита. Оформи название коротко по шаблону для контрибьюта, а текст с детальным описанием опусти ниже по практикам формирования коммита в git

2022-04-22 08:28 UTC, Frechet commented on Dockerfile
> +COPY target/wikibot-1.0-SNAPSHOT.war wikibot.war
Раз spring boot, то jar следует использовать? В чём разница между war и jar упаковке для старта бутового приложения?

2022-04-22 08:30 UTC, Frechet commented on pom.xml
> +        <version>2.6.4</version>
Давай вынесем версии в проперти и согласуем их по всем зависимостям

2022-04-22 10:30 UTC, Nepomnyaschy requested changes

2022-04-22 10:30 UTC, Nepomnyaschy commented on pom.xml
>      <groupId>ru.intabia.wikitabia</groupId>
@Frechet видел у нас в других репах com.intabia, на чем в итоге останавливаемся?

2022-04-22 10:30 UTC, Nepomnyaschy commented on pom.xml
> +            <artifactId>spring-boot-maven-plugin</artifactId>
а почему и тут объявили, и выше в плагинах?

2022-04-22 12:02 UTC, Frechet commented on pom.xml
>      <groupId>ru.intabia.wikitabia</groupId>
com, @MudryPryanik поправь, пожалуйста

2022-05-05 12:07 UTC, MudryPryanik commented on Dockerfile
> +COPY target/wikibot-1.0-SNAPSHOT.war wikibot.war
war исправлен на jar из-за ненадобности

2022-05-05 12:08 UTC, MudryPryanik commented on pom.xml
>      <groupId>ru.intabia.wikitabia</groupId>
исправлено

2022-05-05 12:09 UTC, MudryPryanik commented on pom.xml
> +            <artifactId>spring-boot-maven-plugin</artifactId>
исправлено

2022-05-31 17:17 UTC, merged